name: Docker Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t github-action-workflow-demo .

      - name: Run Docker container
        run: docker run --name github_action_aemo_app -d -p 8080:80 github-action-workflow-demo
